import type { Metadata } from "next";
import PrintButton from "./PrintButton";

export const metadata: Metadata = { title: "CV | Alphonse Afanyu", description: "Professional profile and project experience of Food Process Engineer Alphonse Afanyu." };

const skills = ["Food processing", "Product development and formulation", "Quality assurance and control", "Food safety and HACCP principles", "Good Manufacturing Practices", "Process optimisation", "Laboratory analysis", "Minitab statistical analysis", "Technical documentation"];

export default function CvPage() {
  return <main className="cv-page"><header><div><p>ALPHONSE AFANYU</p><h1>Food Process Engineer</h1><span>Quality Assurance · Food Safety · Food Product Development</span></div><PrintButton /></header>
    <section><h2>Profile</h2><p>Food Process Engineer with an MEng in Biotechnology and Food Process Engineering and practical exposure across food product development, processing, preservation, quality, and research. Based in Bamenda, Cameroon; open to remote, freelance, relocation, and food-industry opportunities.</p></section>
    <div className="cv-columns"><div><section><h2>Selected projects</h2><article><h3>Tomato Processing — Savannah Foods</h3><p>Raw-material processing, product development, processing operations, process monitoring, quality considerations, and product improvement for concentrated tomato products.</p></article><article><h3>Millet-Based Baby Food</h3><p>Master’s project covering formulation, processing, nutritional considerations, product evaluation, research, and experimentation.</p></article><article><h3>Composite-Flour Cookies</h3><p>Bambara groundnut and plantain-peel flour formulation, baking evaluation, nutritional analysis, functional-property evaluation, and formulation comparison. Protein increased from 6.90% to 14.22% in F4.</p></article><article><h3>Shelf-Life Extension of Purees</h3><p>Potassium-sorbate preservation work considering product stability, food safety, and experimental evaluation.</p></article></section><section><h2>Industry exposure</h2><p><strong>Mongan Foods:</strong> Groundnut oil production; dark and milk chocolate production.</p><p><strong>Leelou:</strong> Food production and processing; shelf-life extension work on purees.</p></section></div><aside><section><h2>Education</h2><p><strong>Master of Engineering (MEng)</strong><br />Biotechnology and Food Process Engineering</p></section><section><h2>Technical capabilities</h2><ul>{skills.map(skill => <li key={skill}>{skill}</li>)}</ul></section><section><h2>Contact</h2><p>Bamenda, Cameroon<br /><a href="mailto:alphonseafanyu8@gmail.com">alphonseafanyu8@gmail.com</a><br /><a href="tel:+237653367464">+237 653 367 464</a><br /><a href="https://www.linkedin.com/in/afanyualphonse">LinkedIn</a></p></section></aside></div>
  </main>;
}
